### ISSUE TITLE
Checkpoint Feedback

### ISSUE THREAD

**Issue by stephenjarrell19** [COGS118A/Group003-Sp22#4]
**Total Points: 8 / 8 points**

Project Question/Goal (out of 1): 1/1 points

_Criteria:_
- Clear/Unambiguous in its wording
- Achievable
- Well-specified 

Data (out of 1): 1/1 points

_Criteria:_
- Have at least one dataset 
- Appropriate to the question/goal
- Large enough datapoints ~5 to 10k
- Enough variables to be interesting ~10
- Not m>=n

Data Manipulation (out of 4): 4/4 points

_Criteria:_
  - Cleaned
  - Explored
  - Demonstrate suitability
  - Appropriately transformed (stdscaler, text processing)
  - Identified a subset of features

Baseline Performance /  Preliminary Results (out of 2):  2/2 points

_Criteria:_
- Baseline
- Learning curves
- Validation curves
- Performance across models

Other Notes for the Final Submission:
I LOVE YOUR PROJECT. Awesome job so far. Please keep doing what you're doing! Some notes for the final submission:

When you work on your final, make sure you are explaining your approaches, comparing them, and reasoning about why some may be better. Ex.: Why do particular models seem to do well or poorly? 

What is your process for selecting the best model? Are you purely using metrics, or do you have computational efficiency and parsimony principle in mind? Just be clear, there's no "right answer" here. However, you should be performing hyperparameter tuning, potentially with some form of Grid Search and Cross Validation.

**Comment by Lord-of-Bugs** [comment]
Thanks Stephen, we will for sure look into what's suggested! Glad that you liked our project. Stay tuned for the ultimate!
